name: Deploy Dual Sites to GitHub Pages

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./biryani-modern/package-lock.json
          
      - name: Install dependencies for modern site
        working-directory: ./biryani-modern
        run: npm ci
        
      - name: Build modern site
        working-directory: ./biryani-modern
        run: npm run build
        env:
          NODE_ENV: production
          
      - name: Create deployment directory structure
        run: |
          mkdir -p deploy_site
          # Copy old site files to root
          cp index.html app.js logo.jpg pdf-complete-2page.js deploy_site/
          # Copy preview page
          cp preview.html deploy_site/
          # Create modern subdirectory and copy new site
          mkdir -p deploy_site/modern
          cp -r biryani-modern/dist/* deploy_site/modern/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
